import type { Metadata } from "next";
import Sidebar from "./components/sidebar";
import Topbar from "./components/topbar";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
      >
        <div className="flex h-full">
          <Sidebar />
          <main className="flex-1 overflow-y-auto px-10 bg-[#FAF9F6]">
            <Topbar />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
